
scenario: "maker_space"
with_ros: true
odom_frame: "mobipick/odom"
colors: {
  "0": "Traffic Red",
  "1": "Traffic Yellow",
  "2": "Yellow Green",
  "3": "Traffic Green",
  "4": "Blue",
  "5": "Purple",
  "6": "Telemagenta",
}
weights: {
  "topo_score": 3.,
  "percept_score": 1.,
}
prolog_files: ["reload.pl","rules.pl"]
rule_file: "rules.pl"
reload_file: "reload.pl"
location_offset: [10.305, 2.395, -0.010]
table_locations: {
  "table_1": [13.22, 2.15, 0.00],
  "table_2": [12.07, 3.25, 0.00],
  "table_3": [10.42, 3.25, 0.00],
}
table_sizes: {
  "table_1": [0.70, 1.40, 0.70],
  "table_2": [1.40, 0.70, 0.70],
  "table_3": [1.40, 0.70, 0.70],
}
max_count: {
    "klt": 3,
    "power_drill": 2,
    "multimeter": 1,
    "relay": 1,
    "screwdriver": 1,
}
onto_config: {
  "onto_uri": "http://dfki.ipr.de/onto",
}
