
scenario: "maker_space"
with_ros: true
global_frame: "map"
colors: {
  "0": "Traffic Red",
  "1": "Traffic Yellow",
  "2": "Yellow Green",
  "3": "Traffic Green",
  "4": "Blue",
  "5": "Purple",
  "6": "Telemagenta",
}
weights: {
  "topo_score": 3.,
  "percept_score": 1.,
}
prolog_files: ["reload.pl","rules.pl"]
rule_file: "rules.pl"
reload_file: "reload.pl"
# table locations + sizes from mobipick_labs/tables_demo_bringup/config/ai_day_planning_scene.yaml
table_locations: {
  "table_1": [19.0, 15.16, 0.36],
  "table_2": [19.9, 13.29, 0.3575],
  "table_3": [20.84, 13.29, 0.3575],
  "table_4": [22.14, 15.23, 0.36],
}
table_sizes: {
  "table_1": [0.80, 1.60, 0.72],
  "table_2": [0.80, 0.80, 0.715],
  "table_3": [0.80, 0.80, 0.715],
  "table_4": [0.80, 0.80, 0.72],
}
max_count: {
    "klt": 10,
    "power_drill_with_grip": 2,
    "multimeter": 1,
    "relay": 1,
    "screwdriver": 1,
}
onto_config: {
  "onto_uri": "http://dfki.ipr.de/onto",
}
